* General Overview
The program first reads in the flags from the command line, and verifies them for correctness. Then it creates an array of structs to track the statistics of each inputted tracefile. Next, it creates a hash table for use as the page table, allocate memory for virtual memory. Then it reads all the references from files by calling readRefsFromFiles. It flushes the TLB if necessary, and then performs the necessary additions/lookups by calling addToMemory. Once computation has been completed, it displays it and performs cleanup for termination of the program.
** Pointer to Code 
   c. Look in fileIO.c, and tvm379.c:161

   d. Look at linkedlist.c:123 and memory.c:49

   e. LRU implementation linkedlist.c:169

   f. FIFO implementation in addNewNode linkedlist.c:40

   g. Counters sprinkled through addToMemory:22

   h. 

   i. See 'How Simulator is Efficient and Scalable'

   j. See [[Results][Results]]

   k. See [[Results][Results]]

* How Simulator is Efficient and Scalable
** fileIO.c
  1. In line 54 it reads in the entire (4 * Quantum) bytes, rather than reading in 4 bytes quantum times. This removed a significant bottle neck in our code
** memory.c
  1. traceFileTracker is a "poor man's hash table" indexed by PID, that allows statistics to be tracked for each tracefile in constant time
  2. On line 122 frameBuffer is a hash table used to store pointers to the current nodes in virtualMemory. Giving us near constant time access to seek the nodes.
  3. We are tracking the last PID and last page number to determine automatically if the page is already in the TLB, and therefore do not need to search the TLB linearly. These are checked for before any searching is done
** In General
  1. We tried to minimize iteration as much as possible by having all arrays index on PID or some uniquely identifiable variable to ensure constant time lookup of data
  2. We wrote tests found in the /tests folder to ensure our modules were working as intended 
  3. We maintained separate .c and .h files for each major functionality that are highly independent to ensure that code was easily debuggable and optimized
  4. TLB, all pageTables, and virtualMemory are all represented as doubly linked list. This means that we can dynamically allocate all storage and only use up as much memory as we need at any given time and no more.

* Testing
** Test Suite
  - Run "make test" to run the following test suite:

    	time ./tvm379 1024 128 g 100 800 f heapsort-trace.bin quicksort-trace.bin

    	time ./tvm379 1024 128 g 100 800 l heapsort-trace.bin quicksort-trace.bin

        time ./tvm379 1024 128 g 100 80 f heapsort-trace.bin quicksort-trace.bin
        
        time ./tvm379 1024 128 g 100 80 l heapsort-trace.bin quicksort-trace.bin
        
        time ./tvm379 1024 128 g 100 800 f heapsort-trace.bin
        
        time ./tvm379 1024 128 g 100 800 l heapsort-trace.bin
                
        time ./tvm379 1024 128 g 100 80 f heapsort-trace.bin

        time ./tvm379 1024 128 g 100 80 l heapsort-trace.bin

        time ./tvm379 1024 128 g 100 800 f quicksort-trace.bin

        time ./tvm379 1024 128 g 100 800 l quicksort-trace.bin

        time ./tvm379 1024 128 g 100 80 f quicksort-trace.bin

        time ./tvm379 1024 128 g 100 80 l quicksort-trace.bin

        time ./tvm379 65536 256 g 100 1000000 l heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

        time ./tvm379 16 8 g 10 1 l heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

        time ./tvm379 65536 256 g 100 1000000 f heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

        time ./tvm379 16 8 g 10 1 f heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

        time ./tvm379 65536 256 p 100 1000000 l heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

        time ./tvm379 16 8 p 10 1 l heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

        time ./tvm379 65536 256 p 100 1000000 f heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin
        
        time ./tvm379 16 8 p 10 1 f heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin
* Results
 *** Test Machine Specifications
 - All tests were run on a 2015 MBP
 - Processor: 2.7Gh Intel Core i5
 - Memory 8Gb 1867 Mhz DDR3
 *** Sample Output

#+BEGIN_SRC bash
time ./tvm379 1024 128 g 100 800 f heapsort-trace.bin quicksort-trace.bin

39823095	 93244	 92593		 711.398810
41154468	 6872	 6723		 84.640971
        7.25 real         7.09 user         0.13 sys

time ./tvm379 1024 128 g 100 800 l heapsort-trace.bin quicksort-trace.bin

39824870	 56404	 55726		 718.726178
41154596	 7205	 7083		 77.313509
       11.68 real        10.86 user         0.36 sys

time ./tvm379 1024 128 g 100 80 f heapsort-trace.bin quicksort-trace.bin

39190505	 1978395	 1978325		 73.814592
41108915	 59985	 59975		 6.188825
        6.01 real         5.55 user         0.24 sys

time ./tvm379 1024 128 g 100 80 l heapsort-trace.bin quicksort-trace.bin

39458465	 1710435	 1710365		 73.555660
41152298	 16602	 16592		 6.406009
        7.37 real         7.01 user         0.20 sys

time ./tvm379 1024 128 g 100 800 f heapsort-trace.bin

39766376	 58011	 57211		 792.036306
        6.27 real         6.06 user         0.11 sys

time ./tvm379 1024 128 g 100 800 l heapsort-trace.bin

39767413	 45821	 45021		 792.056215
        8.27 real         8.16 user         0.08 sys

time ./tvm379 1024 128 g 100 80 f heapsort-trace.bin

39138944	 1956456	 1956376		 79.921258
        4.09 real         4.00 user         0.07 sys

time ./tvm379 1024 128 g 100 80 l heapsort-trace.bin

39407989	 1687411	 1687331		 79.923227
        5.20 real         4.87 user         0.13 sys

time ./tvm379 1024 128 g 100 800 f quicksort-trace.bin

41163636	 1798	 998		 792.050524
        1.18 real         1.08 user         0.07 sys

time ./tvm379 1024 128 g 100 800 l quicksort-trace.bin

41163635	 1792	 992		 792.070397
        2.70 real         2.19 user         0.16 sys

time ./tvm379 1024 128 g 100 80 f quicksort-trace.bin

41162782	 6118	 6038		 79.921399
        1.37 real         1.15 user         0.10 sys

time ./tvm379 1024 128 g 100 80 l quicksort-trace.bin

41162832	 6068	 5988		 79.923364
        3.39 real         2.46 user         0.18 sys

time ./tvm379 65536 256 g 100 1000000 l heapsort-trace.bin quicksort-trace.bin 
quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

41168883	 17	 0		 16.808974
41168884	 16	 0		 15.808974
41168884	 16	 0		 15.808974
41168884	 16	 0		 15.808974
41168884	 16	 0		 15.808974
       11.40 real        10.67 user         0.38 sys

time ./tvm379 16 8 g 10 1 l heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin 
heapsort-trace.bin quicksort-trace.bin

0	 41168890	 41168890		 0.900000
0	 41168890	 41168890		 0.900000
0	 41168890	 41168890		 0.900000
0	 41168890	 41168890		 0.900000
0	 41168890	 41168889		 0.900000
       94.20 real        91.14 user         1.01 sys

time ./tvm379 65536 256 g 100 1000000 f heapsort-trace.bin quicksort-trace.bin 
quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin


41168883	 17	 0		 16.808971
41168884	 16	 0		 15.808974
41168884	 16	 0		 15.808974
41168884	 16	 0		 15.808974
41168884	 16	 0		 15.808974
        6.77 real         5.62 user         0.44 sys

time ./tvm379 16 8 g 10 1 f heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin
 heapsort-trace.bin quicksort-trace.bin

21874890	 19294000	 19294000		 0.900000
17247294	 23921596	 23921596		 0.900000
17247294	 23921596	 23921596		 0.900000
21874887	 19294003	 19294003		 0.900000
17247294	 23921596	 23921595		 0.900000
       53.28 real        51.84 user         0.70 sys

time ./tvm379 65536 256 p 100 1000000 l heapsort-trace.bin quicksort-trace.bin 
quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

38996139	 17	 0		 16.808974
40511616	 16	 0		 15.808974
40511616	 16	 0		 15.808974
38996141	 16	 0		 15.808974
40511616	 16	 0		 15.808974
       12.81 real        12.31 user         0.33 sys

time ./tvm379 16 8 p 10 1 l heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin 
heapsort-trace.bin quicksort-trace.bin

0	 41168890	 41168890		 0.900000
0	 41168890	 41168890		 0.900000
0	 41168890	 41168890		 0.900000
0	 41168890	 41168890		 0.900000
0	 41168890	 41168889		 0.900000
      104.13 real        99.27 user         1.31 sys

time ./tvm379 65536 256 p 100 1000000 f heapsort-trace.bin quicksort-trace.bin 
quicksort-trace.bin heapsort-trace.bin quicksort-trace.bin

38996140	 17	 0		 16.808971
40511616	 16	 0		 15.808974
40511616	 16	 0		 15.808974
38996141	 16	 0		 15.808974
40511616	 16	 0		 15.808974
        6.92 real         6.65 user         0.24 sys

time ./tvm379 16 8 p 10 1 f heapsort-trace.bin quicksort-trace.bin quicksort-trace.bin 
heapsort-trace.bin quicksort-trace.bin

21874890	 19294000	 19294000		 0.900000
17247294	 23921596	 23921596		 0.900000
17247294	 23921596	 23921596		 0.900000
21874887	 19294003	 19294003		 0.900000
17247294	 23921596	 23921595		 0.900000
       56.96 real        56.09 user         0.50 sys
#+END_SRC
